### ISSUE TITLE
Actual Sensor Temperature

### ISSUE THREAD

**Issue by ASX9** [KiraPC/ha-switchbot-remote#2]
Please add support to add any sensor to represent actual temperature of the room.

**Comment by KiraPC** [comment]
You can do it via official switchbot integration.

**Comment by ASX9** [comment]
> You can do it via official switchbot integration.

With the official integration I can’t detect IR configured devices.

**Comment by KiraPC** [comment]
Temperature sensor is not IR device

**Comment by ASX9** [comment]
I'm sorry I didn't make myself clear. When the device is displayed in Homekit, the temperature of the climate control sensor is displayed and the temperature assigned to the climate control is displayed as the target temperature. This current temperature is shown with a value of 21 degrees, would it be possible to have this value linked to a sensor in this room?

**Comment by ASX9** [comment]
![IMG_3705](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/32a176e5-e836-4536-91ac-ab6e275e58ce)
![IMG_3704](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/fe6dc13f-5830-42f4-a26e-bd3e26df7440)

**Comment by KiraPC** [comment]
Oh, yes, sure. It's scheduled to implement in future release. I'm quite busy in this period but I know how to implement so it will come soon

**Comment by ASX9** [comment]
Ok, thanks you!! 

Is it also planned to refresh the current status of the device? I mean, for example, when I control the air conditioning from alexa (via Skill Switchbot), with this integration the wrong state remains.

**Comment by KiraPC** [comment]
Unfortunately switchbot does not expose apis for this. I know the app can get the status but I don't know how it does.

It need reverse engineering on the app

**Comment by ASX9** [comment]
All right, I'll keep an eye on the next versions, thanks for your effort.

**Comment by goodsale** [comment]
@KiraPC 

I find your integration great and worked perfectly for me.

We pressure Switchbot to make available the query via API 1.1 to get the status of the air conditioner.

Now the big problem is that if the AC is turned on by GH or Alexa or the Switchbot App Homeassistant can't have the status.

Really Thanks

**Comment by KiraPC** [comment]
Yes I know. Do you already opened an issue on switchbot api GitHub? 

Anyway, I linked HA to Alex and GH so if I use them to turn on the devices I can see the updates

**Comment by ASX9** [comment]
I am considering paying the nabu casa subscription to avoid this problem.

Anyway, I have seen another problem when restarting home assistant it doesn't remember the previous state of the device, would it be possible to save it in some variable that is loaded when starting the addon?

**Comment by KiraPC** [comment]
You can use haska for Alexa integration. There are a lot of guides. 

Anyway, idk about the last state check. HA has a db I'll try to understand how it work

**Comment by goodsale** [comment]
> haska

yes look here:
https://github.com/OpenWonderLabs/SwitchBotAPI/issues/224

**Comment by ASX9** [comment]
> You can use haska for Alexa integration. There are a lot of guides.
> 
> Anyway, idk about the last state check. HA has a db I'll try to understand how it work

Hi, I have managed to configure haaska but I have a problem. When I ask it to turn on the AC it turns it on in heat mode. Is there any way to solve this? I have tried to make a routine but it doesn't give me the option to choose the mode.

**Comment by KiraPC** [comment]
Hi, yes it is an issue. I have already ready the fix but not delivered yet. Tomorrow will be available. Need to understand the release management on HACS but after the tomorrow push you can pull the changes and have the fix

**Comment by KiraPC** [comment]
> > You can use haska for Alexa integration. There are a lot of guides.
> > Anyway, idk about the last state check. HA has a db I'll try to understand how it work
> 
> Hi, I have managed to configure haaska but I have a problem. When I ask it to turn on the AC it turns it on in heat mode. Is there any way to solve this? I have tried to make a routine but it doesn't give me the option to choose the mode.

This error should be fixed in the [0.0.1-alfa.2](https://github.com/KiraPC/ha-switchbot-remote/releases/tag/0.0.1-alfa.2)

**Comment by KiraPC** [comment]
@ASX9 With the release 0.1.0 after you've configured the integration, you can configure your devices (for now just the air conditioner) and adding two sensors, one for humidity and one for temperature.

Let me know

**Comment by ASX9** [comment]
I have updated and on the one hand, the previous status is maintained without any problem but the current temperature and humidity sensors are still not displayed in Homekit. I don't know how I can see if the entities have been linked correctly.

**Comment by KiraPC** [comment]
@ASX9 can you see them on HA? 

Like in my screen
![Screenshot 2023-07-17 alle 17 52 02](https://github.com/KiraPC/ha-switchbot-remote/assets/46629148/54999a7d-5825-4219-bb28-f332040e1a1c)

**Comment by ASX9** [comment]
No, I see this: 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/bcbd1bc5-6746-498f-ba99-24584565bf62)

Is it possible that the entity has been entered incorrectly? I have entered this:
sensor.habitacion_medidor_temperatura

**Comment by KiraPC** [comment]
Mmm. It should be fine in this way. If you check the logs do you see any error from switchbotremote?

**Comment by ASX9** [comment]
Another option, the name of discovered is not the same: 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/935a3683-e41f-4a12-9cf7-9dea59be422a)

**Comment by KiraPC** [comment]
> state(),

This is just a warning there isn't error, so you should have been set the correct sensor. 

I'll check locally asap.

I didn't get the second problem about name different

**Comment by ASX9** [comment]
Ok, I'm not at home right now, when I get home I'll delete the extension and try to discover the devices again.

**Comment by ASX9** [comment]
List of devices: 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/fb07649b-7dea-4cde-bce5-d94d61cf51f2)

Device (Aire Valeria): 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/59f0c2d0-9def-4c68-94e9-68eade12f11b)

**Comment by KiraPC** [comment]
@ASX9 still not understanding. 

Anyway is not an issue. The device and the entity could have different name.

**Comment by KiraPC** [comment]
@ASX9 are you sure you have installed the 0.1.0 because this afteroon I released 2 versions, one (0.0.1-beta.1) has the defect you are facing the 0.1.0 fix this issue

**Comment by KiraPC** [comment]
@ASX9 it's the wrong one. Download with hacs the 0.1.0

**Comment by ASX9** [comment]
Ok, I got this problem with that version: 
<img width="456" alt="image" src="https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/81df0db8-fc8c-443c-9892-0bfc4399426d">

**Comment by KiraPC** [comment]
Ok, please share the logs

**Comment by ASX9** [comment]
Este error se originó a partir de una integración personalizada.

Logger: aiohttp.server
Source: custom_components/switchbotremote/config_flow.py:132 
Integration: SwitchBot Remote IR 
First occurred: 19:43:42 (1 occurrences) 
Last logged: 19:43:42

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 242, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/config_flow.py", line 101, in async_step_init
    return await self.async_step_edit_device()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/config_flow.py", line 132, in async_step_edit_device
    self.config_entry.data[remote.id]
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '02-202307120239-80612249'

**Comment by KiraPC** [comment]
@ASX9 OK, my bad. Please install the 0.1.1 just released

**Comment by ASX9** [comment]
Working!! 
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/7228966/188eccd8-286d-493e-92c5-0ab9d0e8994f)


Thanks you!!

**Comment by KiraPC** [comment]
Perfetto!!

In closing the issue now. 

Share the integration 😁

**Comment by goodsale** [comment]
@KiraPC 

With API 1.1 I think you can easily add the temperature and humidity sensors of the new HUB 2 (matter version).

I leave below the configuration lines that allow the creation of sensors, they work for me in configuration.Yaml after correct authentication.

If these instructions were added in your integration it would be TOP!

In case if I don't have a Hub2 available, I can do the test

```
  - resource: https://api.switch-bot.com/v1.1/devices/HUBDEVICEID/status
    scan_interval: 300
    headers:
      Authorization: "{{ states('input_text.switchbot_token') }}"
      sign: "{{ states('sensor.switchbot_sign') }}"
      t: "{{ state_attr('sensor.switchbot_sign','t') }}"
      Content-Type: "application/json"
      nonce: ""
    sensor:
      - name: "SwitchBot Hub 2 Temperature"
        unique_id: switchbot_hub_2_temperature
        value_template: "{{ value_json.body.temperature }}"
        unit_of_measurement: "°C"
        device_class: temperature
      - name: "SwitchBot Hub 2 Humidity"
        unique_id: switchbot_hub_2_humidity
        value_template: "{{ value_json.body.humidity }}"
        unit_of_measurement: "%"
        device_class: humidity
```

**Comment by KiraPC** [comment]
@goodsale the official integration does not recognize it via bluethoot?

**Comment by goodsale** [comment]
@KiraPC 

I think not.
HUB 2 is a bluetooth hub but cannot be controlled via bluetooth.

To request the temperature or humidity from the HUB 2 you need a dongle matter or API 1.1

I created the sensor with these simple lines in configuration.yaml after successful authentication, if it was already managed by your integration it would be even better.

You can see below that I only get data from a switchbot temperature sensor connected to a HUB (via bluetooth) but not from HUB2 which is not picked up by the official integration in any way

![switchbotscreen](https://github.com/KiraPC/ha-switchbot-remote/assets/6981274/dfb1230d-f0ed-4e6e-a2cd-04eaafa98635)

**Comment by KiraPC** [comment]
@goodsale I supposed was this the problem.

I can try to implement this. Please could you open a new issue here so I can plan the implementation?

I have not the Hub2 so i'll ask you for tests.

Italiano eh? Anche io ;)

**Comment by ASX9** [comment]
Hi, I have two HUB 2 and a Hub mini, and I confirm that they are not detected by the bluetooth integration. Currently they can only be used via matter or api.

**Comment by goodsale** [comment]
@KiraPC 

opend... https://github.com/KiraPC/ha-switchbot-remote/issues/7

Certo! Italiano! 👍
